sonar.projectKey=dapherooo
sonar.projectName=task_approve
sonar.projectVersion=1.0.0
sonar.organization=DAP
sonar.sourceEncoding=UTF-8
sonar.sources=src
sonar.tests=
sonar.exclusions=node_modules/**,dist/**,coverage/**,loadtest/**
sonar.typescript.lcov.reportPaths=coverage/lcov.info
sonar.branch.name=main
